#!/bin/bash
exec brave --password-store=basic --ozone-platform=wayland \
  --force-device-scale-factor=1.0 --disable-background-networking \
  --disable-background-timer-throttling --disable-dev-shm-usage \
  --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer \
  --disable-extensions-http-throttling --memory-pressure-off \
  --max_old_space_size=2048 --disable-background-mode \
  --disable-component-update --process-per-site "$@"
