#!/usr/bin/env bash

set -e

# Install hyprland and dependencies
sudo pacman -S --noconfirm --needed hyprland hyprpaper xdg-desktop-portal-hyprland

paru -S --noconfirm --needed hyprshot hyprpicker-git
